--liquibase formatted sql

--changeset amalik:table_users
CREATE TABLE LIQUIBASE_USER.users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
    username VARCHAR2(50) NOT NULL, 
    email VARCHAR2(100) NOT NULL, 
    status VARCHAR2(20) 
    DEFAULT 'pending' NOT NULL, 
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, 
    CONSTRAINT PK_USERS PRIMARY KEY (id), 
    UNIQUE (username)
);
--rollback DROP TABLE LIQUIBASE_USER.USERS;

--changeset amalik:insert_alice expectedRowCount:1
INSERT INTO users (username, email, status) VALUES ('alice', 'alice@example.com', 'active');
--rollback DELETE from users where username = 'alice'

--changeset amalik:insert_bob expectedRowCount:1
INSERT INTO users (username, email, status) VALUES ('bob', 'bob@example.com', 'active');
--rollback DELETE from users where username = 'bob'

--changeset amalik:insert_charlie expectedRowCount:3
INSERT INTO users (username, email, status) VALUES ('charlie', 'charlie@example.com', 'active');
INSERT INTO users (username, email, status) VALUES ('jeff', 'jeff@example.com', 'active');
INSERT INTO users (username, email, status) VALUES ('david', 'davic@example.com', 'active');
INSERT INTO users (username, email, status) VALUES ('tim', 'tim@example.com', 'active');

--rollback DELETE from users where username = 'charlie'
--rollback DELETE from users where username = 'jeff'
--rollback DELETE from users where username = 'david'
--rollback DELETE from users where username = 'tim'
